### ISSUE TITLE
How to use Horizon as Input?

### ISSUE THREAD

**Issue by whimian** [waynegm/OpendTect-External-Attributes#2]
'Inputs' seems to support only seismic data. I would like to know how to use Horizons as Inputs.

**Comment by waynegm** [comment]
It's not clear to me what you are trying to do. Do you want to extract a seismic attribute along an horizon?

**Comment by whimian** [comment]
I intend to perform computation on seismic data between two horizons.

**Comment by waynegm** [comment]
You need to use the menu option **Processing|Create Seismic Output|Attributes|Between Horizons**. The OpendTect help for this is [here](http://doc.opendtect.org/6.0.0/doc/od_userdoc/Default.htm#processing/create_seismic_output/attributes/between_horizons.htm%3FTocPath%3D6%2520Processing%7C6.1%2520Create%2520Seismic%2520Output%7C6.1.1%2520Attributes%7C_____6)

**Comment by charlandellon** [comment]
Hello,

I would like to know how to use well logs as Inputs.

**Comment by waynegm** [comment]
You have to use the "Processing|Create Seismic Output| Create From Well
Logs" menu option to create a seismic volume for each log which contains
the log values at the well locations. See the OpendTect Documentation for
details.
<http://doc.opendtect.org/6.0.0/doc/od_userdoc/Default.htm#processing/create_seismic_output/create_from_wells.htm%3FTocPath%3D6%2520Processing%7C6.1%2520Create%2520Seismic%2520Output%7C_____5>

Then use the External Attributes plugin with the created volumes as input.
There isn't a way to work with well logs directly from the plugin.
Regards,
Wayne

Regards,
Wayne Mogg
Mob: +61 481 470 504
Hm: +61 7 3263 3987
