### ISSUE TITLE
smooth_LPA stuck on calculating

### ISSUE THREAD

**Issue by whimian** [waynegm/OpendTect-External-Attributes#3]
I'm running Opendtect 6.0.3 on Windows 10 64bits, 

running sooth_LPA script causes Opendtect to be stuck. 

![capture](https://cloud.githubusercontent.com/assets/3821278/26395728/8e53fe5c-40a3-11e7-8e43-2c10cf93686d.PNG)

**Comment by waynegm** [comment]
Can you confirm the parameter screen for the attribute looks like this:
![image](https://cloud.githubusercontent.com/assets/3080502/26398993/b70b14b4-40be-11e7-90d1-772a21410391.png)
and can you show the OpendTect log file (use the Utilities|Show Log File menu) contents
