### ISSUE TITLE
OpendTect External Attributes

### ISSUE THREAD

**Issue by charlandellon** [waynegm/OpendTect-External-Attributes#4]
Hello,
I wonder if the development of python scripts through the External Attribute plugin is limited to working only with scalar parameters and seismic volumes? Well, I would like to have access to other inputs as well: access to horizons to perform operations, wavellets and seismic wells.
How can I access these entries using the External Attribute?

Thank you very much in advance.

Regards,

Charlan.

**Comment by waynegm** [comment]
The plugin only works with seismic volumes but you can use other features in OpendTect to generate seismic volumes from horizons ([Horizon Attribute](http://doc.opendtect.org/6.0.0/doc/od_userdoc/Default.htm#appendix_a-attributes_and_filters/horizon.htm%3FTocPath%3D11%2520Appendix%2520A%2520-%2520Attributes%2520and%2520Filters%7C_____10) )and wells ([Create Seismic from Well](http://doc.opendtect.org/6.0.0/doc/od_userdoc/Default.htm#processing/create_seismic_output/create_from_wells.htm%3FTocPath%3D6%2520Processing%7C6.1%2520Create%2520Seismic%2520Output%7C_____5)) to use with it. Not sure how you would get wavelets into a seismic volume.

Regards,
Wayne

**Comment by charlandellon** [comment]
Hello,
I am very grateful for your return.

I have one more question about how the "extattrib" script works. I see that there is a function called "doCompute" where calculations are made. In this function there is the call of other functions like "doInput and Output" that prepare the input and output data. My question is: If the "doInput and Output" functions define the inputs and outputs respectively, what is the need for the "doInput and Output" functions inside a "while" loop if I already have this data loaded in memory? I would like to understand how the access of the information of my inputs happens, because this has a direct impact on the calculations. I'd like to have more control than is occurring in my scripts.

Thank you very much in advance.

Regards,

Charlan

**Comment by waynegm** [comment]
Have you had a look at the [plugin documentation](http://waynegm.github.io/OpendTect-Plugin-Docs/plugins/ExternalAttrib.html)? In particular the section "Structure of a Conforming Application". 

The External Attribute plugin provides a mechanism to communicate between the OpendTect attribute processing system and a completely separate program, in this case a script running inside a Python interpreter. Information is passed between the script and the External Attribute plugin in OpendTect by using stdin and stdout pipes. OpendTect determines what data is sent there is no control over this from the Python script. From the scripts point of view everything is very atomic. In each pass through the script's "while loop" enough input traces are provided (as specified by the stepouts) to calculate a single output trace. The doInput function reads the set of traces from its stdin pipe. The doOutput function writes the result to the scripts stdout pipe. 

To use this plugin you will have to adapt your algorithm to operate with how the OpendTect attribute calculation system delivers data. It is a bit inefficient but it is also very flexible allowing the same attribute code to output data to elements in the 3D scene (inlines, crosslines, random lines, horizons), crossplots and to new seismic volumes via batch processing.

If you want to control the order of traces being processed you need to look into the OpendTect volume builder or batch processing facility which require delving into C++.
Wayne
